import os
lines = [
    "PROMPT 514 -- feat(cli+site): emit share-ready receipt links and proof URLs in CLI-style product surfaces",
    "=========================================================================================================",
    "Branch: feat/share-ready-proof-surfaces",
    "Base:   feat/receipt-sharing-ui (Prompt 513)",
    "Repo:   TruCore-site",
    "",
    "COMPONENTS / PAGES UPDATED",
    "==========================",
    "1. lib/share-utils.ts (EXTENDED)",
    "   - buildOgPreviewUrl(hash): https://trucore.xyz/api/og/receipt?hash={enc}",
    "   - buildProofBundle(hash): returns { verifyUrl, ogPreviewUrl }",
    "   - Existing buildVerifyUrl unchanged -- no duplication",
    "",
    "2. components/proof-links-card.tsx (NEW)",
    "   Props: hash: string, title?: string, compact?: boolean",
    "   - Renders canonical verify URL + OG preview URL with copy buttons",
    "   - Renders nothing when hash is empty or whitespace",
    "   - Safe clipboard with no raw exceptions",
    "   - Fires telemetry: proof_verify_url_copied, proof_og_url_copied",
    "   - compact=true collapses spacing for secondary surfaces",
    "",
    "3. app/verify/page.tsx (UPDATED)",
    "   - Added ProofLinksCard below ReceiptShareActions when hash is present",
    "   - Reinforces verify page as proof distribution surface",
    "",
    "4. app/customer/dashboard/page.tsx (UPDATED)",
    "   - Added compact ProofLinksCard in success state after share/preview buttons",
    "   - Button-driven sharing stays intact for normal users",
    "   - Raw proof links for power users / developers",
    "",
    "5. app/customer/receipts/page.tsx (UPDATED)",
    "   - Added compact ProofLinksCard in detail panel keyed off content_hash",
    "   - Renders after Full Receipt JSON without redesigning the page",
    "",
    "CANONICAL PROOF LINK STRATEGY",
    "==============================",
    "buildVerifyUrl(hash)    => https://trucore.xyz/verify?hash={encoded}&from=share",
    "buildOgPreviewUrl(hash) => https://trucore.xyz/api/og/receipt?hash={encoded}",
    "buildProofBundle(hash)  => { verifyUrl, ogPreviewUrl }",
    "ProofLinksCard is the single render site. No URL construction in page files.",
    "",
    "TELEMETRY ADDITIONS",
    "===================",
    "proof_verify_url_copied { surface: proof_links_card }",
    "proof_og_url_copied     { surface: proof_links_card }",
    "Pattern: fire-and-forget POST /api/track. No UX breakage. No PII.",
    "",
    "TESTS ADDED AND RESULTS",
    "=======================",
    "NEW: tests/proof-links-card.test.tsx  (19 tests -- all PASSED)",
    "  * Canonical URL helpers (buildVerifyUrl, buildOgPreviewUrl)",
    "  * Special-char encoding correctness",
    "  * Renders verify/OG URLs correctly",
    "  * Renders nothing when hash empty/whitespace",
    "  * Custom title prop",
    "  * Copy verify URL -> clipboard + telemetry event",
    "  * Copy OG URL -> clipboard + telemetry event",
    "  * Copy feedback state (Copied)",
    "  * No throw on clipboard failure",
    "",
    "UPDATED: tests/receipt-sharing-ui.test.tsx (17 tests -- all PASSED)",
    "  * Added vi.mock for trackEvent",
    "  * Added: verify success surface includes proof links (4 tests)",
    "  * Added: dashboard success surface includes proof links (2 tests)",
    "",
    "Total: 36 tests PASSED (0 failures)",
    "Lint:  0 errors, 5 pre-existing warnings (none from new files)",
    "Build: Clean -- all routes compiled successfully",
    "",
    "ACCEPTANCE CRITERIA STATUS",
    "==========================",
    "[PASS] Canonical verify URL emitted in success/verification surfaces",
    "[PASS] Canonical OG preview URL emitted in success/verification surfaces",
    "[PASS] Users can copy proof links directly",
    "[PASS] No sensitive data exposed",
    "[PASS] Reusable ProofLinksCard avoids duplication",
    "[PASS] Existing sharing UX (ReceiptShareActions, buttons) remains intact",
    "[PASS] No new dependencies",
    "[PASS] Lint / build / tests pass",
    "",
    "RISKS / FOLLOW-UPS",
    "==================",
    "1. P2: Receipts page renders proof links only when content_hash is present.",
    "   Consider falling back to receipt_id if content_hash is absent.",
    "2. P2: ProofLinksCard on verify page shows for any hash in URL params,",
    "   not just verified ones. Could gate on verifyStatus===verified.",
    "3. P3: Telemetry surface only. Richer context needs prop threading.",
    "4. P3: compact=true omits explainer note. May warrant tooltip in future.",
    "5. P4: No A/B testing for placement. Additive and non-disruptive.",
    "",
    "Git: feat/share-ready-proof-surfaces pushed to origin.",
]
path = "/home/kontractkoder/repo/agent-transaction-firewall/SUMMARY.txt"
with open(path, "w") as f:
    f.write("\n".join(lines))
print("written OK:", os.path.getsize(path), "bytes")
