import type { Metadata } from "next";
import { ReceiptsList } from "@/components/receipts-list";
import { Badge } from "@/components/ui/badge";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { demoReceipts } from "@/lib/demo-receipts";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Public Receipts Explorer",
  description:
    "Inspect deterministic ATF demo receipts with status, invariant checks, reasons, and receipt hashes.",
  openGraph: {
    title: "Public Receipts Explorer",
    description:
      "Inspect deterministic ATF demo receipts with status, invariant checks, reasons, and receipt hashes.",
    images: [
      {
        url: "/receipts/opengraph-image",
        width: 1200,
        height: 630,
        alt: "TruCore receipts social preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Public Receipts Explorer",
    description:
      "Inspect deterministic ATF demo receipts with status, invariant checks, reasons, and receipt hashes.",
    images: ["/receipts/opengraph-image"],
  },
};

export default function ReceiptsPage() {
  return (
    <Container>
      <Section className="fade-in-up">
        <div className="max-w-3xl">
          <Badge className="mb-4">Public Explorer</Badge>
          <h1 className="text-4xl font-bold tracking-tight text-accent-200 sm:text-6xl">
            Receipts Explorer
          </h1>
          <p className="mt-4 text-xl leading-[1.5] text-slate-200">
            Inspect deterministic receipt artifacts from ATF simulator executions.
          </p>
          <p className="mt-3 text-sm text-slate-300">
            These are deterministic demo receipts generated by the public simulator. No partner data is exposed.
          </p>
          <p className="mt-2 text-sm text-primary-200/80">
            Real Jupiter swaps on Solana can now be finalized into canonical tamper-evident receipts issued by ATF.
          </p>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link
              href="/demo"
              className="inline-flex items-center justify-center rounded-xl border border-primary-300/40 bg-primary-500/15 px-5 py-2 text-sm font-semibold text-primary-100 transition-colors hover:bg-primary-500/25"
            >
              See Demo Live stream
            </Link>
          </div>
        </div>
      </Section>

      <Section className="pt-0 fade-in-up fade-delay-1">
        <ReceiptsList receipts={demoReceipts} />
      </Section>
    </Container>
  );
}
