import type { Metadata } from "next";
import { ReceiptsList } from "@/components/receipts-list";
import { Badge } from "@/components/ui/badge";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { demoReceipts } from "@/lib/demo-receipts";

export const metadata: Metadata = {
  title: "Public Receipts Explorer",
  description:
    "Inspect deterministic ATF demo receipts with status, invariant checks, reasons, and receipt hashes.",
};

export default function ReceiptsPage() {
  return (
    <Container>
      <Section className="fade-in-up">
        <div className="max-w-3xl">
          <Badge className="mb-4">Public Explorer</Badge>
          <h1 className="text-4xl font-bold tracking-tight text-[#ffe0b2] sm:text-6xl">
            Receipts Explorer
          </h1>
          <p className="mt-4 text-xl leading-[1.5] text-slate-200">
            Inspect deterministic receipt artifacts from ATF simulator executions.
          </p>
          <p className="mt-3 text-sm text-slate-300">
            These are deterministic demo receipts generated by the public simulator. No partner data is exposed.
          </p>
        </div>
      </Section>

      <Section className="pt-0 fade-in-up fade-delay-1">
        <ReceiptsList receipts={demoReceipts} />
      </Section>
    </Container>
  );
}
