import type { Metadata } from "next";
import Link from "next/link";
import { VerifyReceiptForm } from "@/components/verify-receipt-form";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";
import { TrackedLink } from "@/components/tracked-link";

interface PageProps {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

export const metadata: Metadata = {
  title: "Verify ATF Receipt Hash",
  description: "Validate deterministic receipt hashes generated by Agent Transaction Firewall.",
};

function parseHash(raw: string | string[] | undefined): string {
  if (typeof raw !== "string") {
    return "";
  }

  return raw;
}

function parseFrom(raw: string | string[] | undefined): "verify" | "receipts" | "portal" | "share" {
  if (raw === "receipts" || raw === "portal" || raw === "share") {
    return raw;
  }

  return "verify";
}

function parseAutofetchSig(raw: string | string[] | undefined): boolean {
  return raw === "1";
}

export default async function VerifyReceiptPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const initialHash = parseHash(params.hash);
  const initialFrom = parseFrom(params.from);
  const shouldAutofetchSignature = parseAutofetchSig(params.autofetchSig);
  const isFromShare = initialFrom === "share";

  return (
    <Container>
      <Section className="fade-in-up">
        <div className="max-w-3xl space-y-5">
          {/* Shared receipt banner - shown when arriving from share link */}
          {isFromShare && initialHash && (
            <div className="rounded-lg border border-primary-400/30 bg-primary-500/10 p-4 space-y-2">
              <div className="flex items-center gap-2">
                <span className="text-lg">&#x1F517;</span>
                <p className="text-sm font-medium text-primary-200">
                  Someone shared a protected trade receipt with you
                </p>
              </div>
              <p className="text-xs text-slate-400">
                Verify this trade was protected by TruCore ATF. The hash below is pre-filled from the shared link.
              </p>
            </div>
          )}

          <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">Verification Utility</p>
          <h1 className="text-4xl font-bold tracking-tight text-accent-200 sm:text-6xl">Verify Receipt Hash</h1>
          <p className="text-xl leading-[1.5] text-slate-300">
            Validate receipt integrity with hash checks, signature verification, and deterministic demo recompute.
          </p>
          <p className="text-sm text-slate-500">Developer utility for independent, copy-paste verification workflows.</p>

          {/* ── Proof-first explainer ── */}
          <div className="rounded-lg border border-accent-500/20 bg-accent-500/[0.04] p-4 space-y-2">
            <p className="text-sm font-semibold text-accent-300">What does verification prove?</p>
            <p className="text-sm leading-relaxed text-slate-300">
              Every policy-governed execution produces a deterministic receipt. Verification confirms
              that a specific execution occurred under a declared policy, with an independently
              recomputable hash. Receipts are useful for bot operators, agent builders, and
              integrators who need inspectable, shareable proof of execution behavior.
            </p>
          </div>

          {/* ── What verification is useful for ── */}
          <div className="space-y-1.5">
            <p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">What verification is useful for</p>
            <ul className="list-disc pl-4 space-y-1 text-sm text-slate-400">
              <li>Confirm a protected execution happened under a specific policy</li>
              <li>Inspect execution receipts and recompute hashes independently</li>
              <li>Share reproducible proof with teammates, auditors, or partners</li>
            </ul>
          </div>

          {/* ── Cold-traffic nudge ── */}
          <p className="text-sm text-slate-400">
            Don&apos;t have a receipt yet?{" "}
            <Link
              href="/docs/first-protected-trade"
              className="font-semibold text-primary-200 transition-colors hover:text-primary-100"
            >
              Run your first protected trade
            </Link>{" "}
            to generate one, or explore the{" "}
            <Link
              href="/builders"
              className="font-semibold text-primary-200 transition-colors hover:text-primary-100"
            >
              builder resources
            </Link>
            .
          </p>

          <div className="gradient-divider" aria-hidden="true" />
          <p className="text-sm text-slate-400">
            Need the normative contract? See{" "}
            <Link
              href="/docs/receipt-specification-v1"
              className="font-semibold text-primary-200 transition-colors hover:text-primary-100"
            >
              Receipt Specification v1
            </Link>
            .
          </p>
        </div>
      </Section>

      <Section className="pt-0 fade-in-up fade-delay-1">
        <VerifyReceiptForm
          initialHash={initialHash}
          initialFrom={initialFrom}
          shouldAutofetchSignature={shouldAutofetchSignature}
        />
      </Section>

      {/* ── Try TruCore CTA for shared link visitors ── */}
      {isFromShare && (
        <Section className="pt-0 fade-in-up fade-delay-1">
          <div className="max-w-3xl">
            <div className="rounded-xl border border-accent-400/30 bg-gradient-to-br from-accent-500/10 to-transparent p-6">
              <h2 className="text-xl font-bold text-accent-200">Protect your trades too</h2>
              <p className="mt-2 text-sm text-slate-300">
                TruCore ATF protects every transaction your agent makes. Get verifiable receipts,
                enforce risk policies, and share proof of protected execution.
              </p>
              <div className="mt-4 flex flex-wrap gap-3">
                <TrackedLink
                  href="/signup"
                  eventName="verify_share_signup_click"
                  eventProps={{ location: "verify_page_share_banner" }}
                  className="rounded-lg bg-accent-500 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-accent-400"
                >
                  Get started free
                </TrackedLink>
                <TrackedLink
                  href="/docs/first-protected-trade"
                  eventName="verify_share_learn_click"
                  eventProps={{ location: "verify_page_share_banner" }}
                  className="rounded-lg border border-white/10 bg-white/5 px-5 py-2.5 text-sm font-medium text-slate-200 transition hover:bg-white/10"
                >
                  Learn how it works
                </TrackedLink>
              </div>
            </div>
          </div>
        </Section>
      )}

      {/* ── Next steps ── */}
      <Section divider className="fade-in-up fade-delay-2">
        <div className="max-w-3xl">
          <h2 className="text-2xl font-bold tracking-tight text-accent-300">What to do next</h2>
          <p className="mt-2 text-sm text-slate-400">
            Haven&apos;t protected a trade yet? Start with the golden path. Already verified? Explore deeper integration.
          </p>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <TrackedLink
              href="/docs/first-protected-trade"
              eventName="verify_next_golden_path_click"
              eventProps={{ location: "verify_page" }}
              className="block rounded-lg border border-accent-500/20 bg-accent-500/[0.04] p-4 transition-colors hover:border-primary-300/30"
            >
              <span className="font-semibold text-accent-300">First protected trade</span>
              <span className="mt-1 block text-sm text-slate-400">Protect an intent, get a receipt, verify it. Start here if you haven&apos;t yet.</span>
            </TrackedLink>
            <TrackedLink
              href="/portal"
              eventName="verify_next_portal_click"
              eventProps={{ location: "verify_page" }}
              className="block rounded-lg border border-white/10 bg-neutral-900/50 p-4 transition-colors hover:border-primary-300/30"
            >
              <span className="font-semibold text-accent-300">Your portal</span>
              <span className="mt-1 block text-sm text-slate-400">View your API keys, usage, and verify receipts from your own activity.</span>
            </TrackedLink>
            <TrackedLink
              href="/docs/receipt-specification-v1"
              eventName="verify_next_receipt_spec_click"
              eventProps={{ location: "verify_page" }}
              className="block rounded-lg border border-white/10 bg-neutral-900/50 p-4 transition-colors hover:border-primary-300/30"
            >
              <span className="font-semibold text-accent-300">Receipt specification</span>
              <span className="mt-1 block text-sm text-slate-400">Normative contract, hash rules, version policy.</span>
            </TrackedLink>
            <TrackedLink
              href="/builders"
              eventName="verify_next_builders_click"
              eventProps={{ location: "verify_page" }}
              className="block rounded-lg border border-white/10 bg-neutral-900/50 p-4 transition-colors hover:border-primary-300/30"
            >
              <span className="font-semibold text-accent-300">For bot builders</span>
              <span className="mt-1 block text-sm text-slate-400">Integration paths, resources, and early access.</span>
            </TrackedLink>
          </div>
        </div>
      </Section>
    </Container>
  );
}