import type { Metadata } from "next";
import Link from "next/link";
import { VerifyReceiptForm } from "@/components/verify-receipt-form";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";

interface PageProps {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

export const metadata: Metadata = {
  title: "Verify ATF Receipt Hash",
  description: "Validate deterministic receipt hashes generated by Agent Transaction Firewall.",
};

function parseHash(raw: string | string[] | undefined): string {
  if (typeof raw !== "string") {
    return "";
  }

  return raw;
}

function parseFrom(raw: string | string[] | undefined): "verify" | "receipts" | "portal" {
  if (raw === "receipts" || raw === "portal") {
    return raw;
  }

  return "verify";
}

function parseAutofetchSig(raw: string | string[] | undefined): boolean {
  return raw === "1";
}

export default async function VerifyReceiptPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const initialHash = parseHash(params.hash);
  const initialFrom = parseFrom(params.from);
  const shouldAutofetchSignature = parseAutofetchSig(params.autofetchSig);

  return (
    <Container>
      <Section className="fade-in-up">
        <div className="max-w-3xl space-y-4">
          <h1 className="text-4xl font-bold tracking-tight text-[#ffe0b2] sm:text-6xl">Verify Receipt Hash</h1>
          <p className="text-xl leading-[1.5] text-slate-200">
            Validate receipt integrity with hash checks, signature verification, and deterministic demo recompute.
          </p>
          <p className="text-sm text-slate-400">Developer utility for independent, copy-paste verification workflows.</p>
          <p className="text-sm text-slate-300">
            Need the normative contract, see{" "}
            <Link
              href="/docs/receipt-specification-v1"
              className="font-semibold text-primary-100 transition-colors hover:text-primary-200"
            >
              Receipt Specification v1
            </Link>
            .
          </p>
        </div>
      </Section>

      <Section className="pt-0 fade-in-up fade-delay-1">
        <VerifyReceiptForm
          initialHash={initialHash}
          initialFrom={initialFrom}
          shouldAutofetchSignature={shouldAutofetchSignature}
        />
      </Section>
    </Container>
  );
}